### ISSUE TITLE
[Bug] Screenshot taking top left corner only

### ISSUE THREAD

**Issue by bcouetil** [asciidoctor/asciidoctorj-screenshot#13]
Thank you for this useful extension.

Using this code under maven inspired from the pom.xml example : 
`screenshot::https://bcouetil.gitlab.io/academy/sample/reveal/reveal-my-asciidoc.html[asciidoctorj-screenshot,dimension=640x480]`

The module opens chrome, resizes it, And I can see that everything is there : 
![chrome-screenshot](https://user-images.githubusercontent.com/42612335/51073998-49694380-1679-11e9-8173-681b32e2998d.jpg)

But on the result image, I see only the top left corner : 
![asciidoctorj-screenshot](https://user-images.githubusercontent.com/42612335/51073979-e8417000-1678-11e9-9cf3-6af1c6b3d65a.png)

- Is is expected ?
- If so, I do I get all what Chrome displays ?
- `dimension `resizes before the screenshot, how to resize after ? Like when we use `width=800` in asciidoc file.

Thanks.

**Comment by sclassen** [comment]
I tried to reproduce you behavior with the URL https://bcouetil.gitlab.io/academy/sample/reveal/reveal-my-asciidoc.html

It works on my machine :wink: 
Since I cannot reproduce I try to help you understand how the plugin works internally. Maybe this helps.

If you do not specify a `selector` then the screenshot will contain all content of your browser without the navigation bar on top.
The browser window is resized before the screenshot is taken. But there is a little caveat to it.
It is almost impossible to calculate the size of the window without taking a screenshot. So to deliver an image with the requested dimension the window is made a little bit too big and then the image is cropped.

But I only add 25 pixels to the compensate for this inaccuracy.

Can you try the following:
In your asciidoc file, before you take the screenshot add the following block
```
[geb, dimension=300x300]
....
go "https://bcouetil.gitlab.io/academy/sample/reveal/reveal-my-asciidoc.html"
sleep 10000
....
```
This should display the page for 10 seconds in the browser window controlled by the screenshot extension. That should give you time to visually compare what you see with what ends up in the image

**Comment by bcouetil** [comment]
I found why : I'm on Windows, with a 125% zoom. Getting back to 100%, there is still some croping, but now it's acceptable, thanks 😄 

![asciidoctorj-screenshot](https://user-images.githubusercontent.com/42612335/51146322-c7367600-1856-11e9-8c57-20f8c7d5805b.png)

**Comment by bcouetil** [comment]
There is still the last question : how do I do an after-screenshot resize ? I mean set the display size.

**Comment by sclassen** [comment]
You can do it with a `[geb, dimension=300x300]` block (see example in previous answer).
try an empty one, if it doesn't work add sleep 1 or some other noop inside

**Comment by bcouetil** [comment]
Thank you.

Using this code : 

```
screenshot::https://bcouetil.gitlab.io/academy/sample/reveal/reveal-my-asciidoc.html[asciidoctorj-screenshot,dimension=1024x780]

[geb, dimension=300x300]
....
sleep 1
....
```
It does the first screenshot 1024x768, then fails : 

`[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc (asciidoc-to-revealjs) on project cg-asciidoctor-sample: Execution asciidoc-to-revealjs of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.6:process-asciidoc failed: org.jruby.exceptions.RaiseException: (RuntimeError) Could not find a converter to handle transform: skip`

Same with empty block. And just putting `[geb, dimension=300x300]` without block does nothing more than the first screenshot.

**Comment by sclassen** [comment]
@mojavelinux Maybe you can help me out here

The screenshot extension replaces the block
```
[geb, dimension=300x300]
....
sleep 1
....
```

with a block that has `skip` as context. This works fine with the regular HTML converter but the revealjs converter does not accept the skip block.
Is there another way to tell asciidoctor that the block should not be included in the output?

Or should we open a ticket for the revealjs converter to support skip blocks?

**Comment by bcouetil** [comment]
Wouldn't it be simpler if the writer were to write something like : 
`screenshot::https://bcouetil.gitlab.io/academy/sample/reveal/reveal-my-asciidoc.html[asciidoctorj-screenshot,dimension=1024x780,width=600]`

And at runtime your code does the screenshot, then replace the block with : 
`image:<dir>/asciidoctorj-screenshot.jpg[asciidoctorj-screenshot,width=600]`

And then let traditional Asciidoctor code take care of the resize ?

But that's fine for now, I let the two sizes be the same, it's working well enough.

**Comment by sclassen** [comment]
The cropping is necessary for the images which are framed using the `browser`, `iphone5` or `nexus5`.
Otherwise the image would overlap with the frame.
